class Main {
    boolean doesOilFloatOnWater(){
        return true;
    }
    boolean doIWantToFly(){
        return true;
    }
    boolean IsItRainingOutside(){
        return true;
    }
    
    void cry(){}
    void fly(){}
    void die(){}
    void coverMyselfInOil(){}
    void openWindow(){}
    void jumpOut(){}
    void goToHell(){}
    void discussTrickleDownEconomicsWithRonaldReagan(){}
    void getReborn(){}



    while (doesOilFloatOnWater()){
        if (doIWantToFly()){
            coverMyselfInOil();
            openWindow();
            jumpOut();
            while (isItRainingOutside()){
                fly();
            }
                die();
                goToHell();
                discussTrickleDownEconomicsWithRonaldReagan();
                getReborn();
        }
    }
        cry();
}